version: '3'
services:
  app:
    ports:
    - "3000:3000"
    - "5000:9000"
    volumes:
    - .:/app

  database:  
    ports:
    - "3306:3306"
    volumes:
    - ./provision/database/structure.sql:/docker-entrypoint-initdb.d/0.sql

  test_database:  
    ports:
    - "3307:3306"
    volumes:
    - ./provision/database/structure.sql:/docker-entrypoint-initdb.d/0.sql